<?php

/**
 * Plugin Name:       MM CORE Bulk Post Generator
 * Plugin URI:        https://budiharyono.id/
 * Description:       Core functionality plugin for shortcodes, schema, and custom fields generated by MM Bulk Post Generator. This plugin must always be active.
 * Version:           1.0.0
 * Author:            Budi Haryono
 * Author URI:        https://budiharyono.id/
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       mm-core-bulk-post-generator
 * Domain Path:       /languages
 * Requires at least: 5.0
 * Requires PHP:      7.0
 */

// Mencegah akses langsung ke file
if (! defined('ABSPATH')) {
    exit;
}




// ======================================================================
// KONFIGURASI UPDATER OTOMATIS - VERSI BARU
// ======================================================================

// URL dasar menuju API di situs repository Anda.
// Cukup ganti domain jika perlu, sisanya biarkan sama.
$my_repo_base_url = 'https://repo.budiharyono.id/wp-json/mm-repo/v1/info/';

// ======================================================================
// KODE PEMANGGIL UPDATER - JANGAN UBAH BAGIAN DI BAWAH INI
// ======================================================================

// Pastikan fungsi get_plugin_data sudah ada.
if (!function_exists('get_plugin_data')) {
    require_once(ABSPATH . 'wp-admin/includes/plugin.php');
}

// 1. Ambil slug plugin secara dinamis dari 'Text Domain' di header.
$plugin_data = get_plugin_data(__FILE__);
$my_plugin_slug = $plugin_data['TextDomain'];

// 2. Buat URL API lengkap secara dinamis.
$my_plugin_api_url = $my_repo_base_url . $my_plugin_slug;

// 3. Muat pustaka updater.
require_once __DIR__ . '/lib/updater.php';

// 4. Daftarkan hook aktivasi.
register_activation_hook(__FILE__, ['My_Plugin_Updater_Library', 'on_activation']);

// 5. Inisialisasi updater jika di area admin.
if (is_admin()) {
    new My_Plugin_Updater_Library(__FILE__, $my_plugin_slug, $my_plugin_api_url);
}

// ----------------------------------------------------------------------
//
// Tempatkan kode fungsional plugin Anda di sini...
//
// ----------------------------------------------------------------------


//---------------------------------------
// PLUGIN Start
//---------------------------------------


// Mendefinisikan konstanta plugin
define('MMCBG_PLUGIN_PATH', plugin_dir_path(__FILE__));

// Memuat file-file fungsionalitas
require_once MMCBG_PLUGIN_PATH . 'includes/shortcodes.php';
require_once MMCBG_PLUGIN_PATH . 'includes/schema-generator.php';
require_once MMCBG_PLUGIN_PATH . 'includes/acf-integration.php';

/**
 * Fungsi penanda bahwa plugin Core sudah dimuat.
 * Plugin generator akan memeriksa keberadaan fungsi ini.
 * @return bool
 */
function mmcbpg_core_loaded()
{
    return true;
}

/**
 * Menambahkan halaman pengaturan untuk plugin Core.
 */
function mmcbpg_add_settings_page()
{
    add_options_page(
        'MM Core Settings',                  // Judul Halaman
        'MM Core BPG Settings',              // Judul Menu
        'manage_options',                    // Kapabilitas
        'mm-core-bulk-post-generator',       // Menu Slug
        'mmcbpg_render_settings_page'        // Fungsi render
    );
}
add_action('admin_menu', 'mmcbpg_add_settings_page');

/**
 * Merender halaman pengaturan.
 */
function mmcbpg_render_settings_page()
{
    require_once MMCBG_PLUGIN_PATH . 'includes/settings-page.php';
}

/**
 * Mendaftarkan pengaturan agar bisa disimpan.
 */
function mmcbpg_register_settings()
{
    register_setting('mmcbpg_settings_group', 'mmcbpg_activate_schema_default');
    register_setting('mmcbpg_settings_group', 'mmcbpg_disable_comments_default');
}
add_action('admin_init', 'mmcbpg_register_settings');
